CREATE TABLE chat_room (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_id BIGINT NOT NULL,
    last_message_sequence BIGINT NOT NULL DEFAULT 0,
    last_message_preview VARCHAR(255),
    last_message_at TIMESTAMP(6),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),

    CONSTRAINT fk_chat_room_trade
        FOREIGN KEY (trade_id) REFERENCES trade (id)
);

CREATE TABLE chat_room_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_room_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    last_read_message_sequence BIGINT NOT NULL DEFAULT 0,
    joined_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),

    CONSTRAINT fk_chat_room_member_room
        FOREIGN KEY (chat_room_id) REFERENCES chat_room (id) ON DELETE CASCADE,

    CONSTRAINT fk_chat_room_member_member
        FOREIGN KEY (member_id) REFERENCES member (id),

    CONSTRAINT uk_chat_room_member_room_member
        UNIQUE (chat_room_id, member_id)
);

CREATE INDEX idx_chat_room_trade_id
    ON chat_room (trade_id);

CREATE INDEX idx_chat_room_member_member_id
    ON chat_room_member (member_id);
