CREATE TABLE refresh_token (
                               id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               member_id   BIGINT       NOT NULL,
                               token_hash  VARCHAR(64)  NOT NULL,
                               family_id   VARCHAR(36)  NOT NULL,
                               expires_at  TIMESTAMP(6) NOT NULL,
                               revoked_at  TIMESTAMP(6),
                               created_at  TIMESTAMP(6),
                               updated_at  TIMESTAMP(6),
                               CONSTRAINT uk_refresh_token_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_refresh_token_member_id  ON refresh_token (member_id);
CREATE INDEX idx_refresh_token_family_id  ON refresh_token (family_id);
CREATE INDEX idx_refresh_token_expires_at ON refresh_token (expires_at);
