CREATE TABLE search_synonym
(
    id           BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    synonym_set  VARCHAR(100) NOT NULL,
    rule_key     VARCHAR(100) NOT NULL,
    synonyms     VARCHAR(500) NOT NULL,
    CONSTRAINT uk_search_synonym_set_rule_key UNIQUE (synonym_set, rule_key)
);
