CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE gacha (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255),
                       caption TEXT,
                       thumbnail_url VARCHAR(1000),
                       instagram_media_id VARCHAR(255),
                       created_at TIMESTAMP(6),
                       updated_at TIMESTAMP(6),

                       CONSTRAINT uk_gacha_instagram_media_id UNIQUE (instagram_media_id)
);

CREATE TABLE store (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       thumbnail_url VARCHAR(255),
                       latitude DOUBLE PRECISION NOT NULL,
                       longitude DOUBLE PRECISION NOT NULL,
                       location GEOMETRY(Point, 4326),
                       created_at TIMESTAMP(6),
                       updated_at TIMESTAMP(6)
);

CREATE TABLE store_detail (
                              store_id BIGINT PRIMARY KEY,
                              name VARCHAR(255) NOT NULL,
                              address VARCHAR(255) NOT NULL,
                              business_hours VARCHAR(255),
                              payment_methods VARCHAR(255),
                              phone VARCHAR(255),
                              instagram_id VARCHAR(255),
                              machine_amount INTEGER,
                              kuji_amount INTEGER,
                              coin_price BIGINT,
                              gacha_min_price BIGINT,
                              gacha_max_price BIGINT,
                              kuji_min_price BIGINT,
                              kuji_max_price BIGINT,
                              select_gacha_min_price BIGINT,
                              select_gacha_max_price BIGINT,
                              has_random_box BOOLEAN,
                              has_select_gacha BOOLEAN,
                              created_at TIMESTAMP(6),
                              updated_at TIMESTAMP(6),

                              CONSTRAINT fk_store_detail_store
                                  FOREIGN KEY (store_id) REFERENCES store (id)
);

CREATE TABLE store_facility (
                                store_id BIGINT NOT NULL,
                                facility VARCHAR(255),

                                CONSTRAINT fk_store_facility_store
                                    FOREIGN KEY (store_id) REFERENCES store_detail (store_id)
);

CREATE TABLE store_image (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             store_id BIGINT NOT NULL,
                             image_url VARCHAR(255) NOT NULL,

                             CONSTRAINT fk_store_image_store
                                 FOREIGN KEY (store_id) REFERENCES store (id)
);

CREATE TABLE gacha_image (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             gacha_id BIGINT NOT NULL,
                             image_url VARCHAR(255) NOT NULL,

                             CONSTRAINT fk_gacha_image_gacha
                                 FOREIGN KEY (gacha_id) REFERENCES gacha (id)
);

CREATE TABLE store_gacha (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             store_id BIGINT NOT NULL,
                             gacha_id BIGINT NOT NULL,

                             CONSTRAINT fk_store_gacha_store
                                 FOREIGN KEY (store_id) REFERENCES store (id),

                             CONSTRAINT fk_store_gacha_gacha
                                 FOREIGN KEY (gacha_id) REFERENCES gacha (id)
);

CREATE INDEX idx_store_image_store_id
    ON store_image (store_id);

CREATE INDEX idx_gacha_image_gacha_id
    ON gacha_image (gacha_id);

CREATE INDEX idx_store_gacha_store_id
    ON store_gacha (store_id);

CREATE INDEX idx_store_gacha_gacha_id
    ON store_gacha (gacha_id);

CREATE INDEX idx_store_location_geography
    ON store
    USING GIST ((location::geography));
