CREATE TABLE category (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(100) NOT NULL UNIQUE
);
CREATE TABLE gacha_category (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                gacha_id BIGINT NOT NULL,
                                category_id BIGINT NOT NULL,
                                CONSTRAINT fk_gacha_category_gacha FOREIGN KEY (gacha_id) REFERENCES gacha(id) ON DELETE CASCADE,
                                CONSTRAINT fk_gacha_category_category FOREIGN KEY (category_id) REFERENCES category(id) ON DELETE CASCADE
);
ALTER TABLE gacha DROP COLUMN IF EXISTS category;
