CREATE TABLE member (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        oauth_id              VARCHAR(255),
                        oauth_provider        VARCHAR(50),
                        oauth_username        VARCHAR(255),
                        nickname              VARCHAR(255),
                        profile_image_url     VARCHAR(255),
                        desire_trade_location VARCHAR(255),
                        is_deleted            BOOLEAN      NOT NULL DEFAULT FALSE,
                        deleted_at            TIMESTAMP,
                        created_at            TIMESTAMP,
                        updated_at            TIMESTAMP
);
