CREATE TABLE trade (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        member_id BIGINT NOT NULL,
                        title VARCHAR(255) NOT NULL,
                        description TEXT,
                        desired_production VARCHAR(255),
                        purchase_store_address VARCHAR(255),
                        trade_place VARCHAR(255),
                        available_time TIMESTAMP(6),
                        status VARCHAR(20) NOT NULL,
                        created_at TIMESTAMP(6),
                        updated_at TIMESTAMP(6),

                        CONSTRAINT fk_trade_member
                            FOREIGN KEY (member_id) REFERENCES member (id)
);

CREATE TABLE trade_category (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 trade_id BIGINT NOT NULL,
                                 category_id BIGINT NOT NULL,
                                 CONSTRAINT fk_trade_category_trade FOREIGN KEY (trade_id) REFERENCES trade(id) ON DELETE CASCADE,
                                 CONSTRAINT fk_trade_category_category FOREIGN KEY (category_id) REFERENCES category(id) ON DELETE CASCADE
);

CREATE TABLE trade_image (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             trade_id BIGINT NOT NULL,
                             image_url VARCHAR(255) NOT NULL,

                             CONSTRAINT fk_trade_image_trade
                                 FOREIGN KEY (trade_id) REFERENCES trade (id)
);

CREATE INDEX idx_trade_member_id
    ON trade (member_id);

CREATE INDEX idx_trade_category_trade_id
    ON trade_category (trade_id);

CREATE INDEX idx_trade_category_category_id
    ON trade_category (category_id);

CREATE INDEX idx_trade_image_trade_id
    ON trade_image (trade_id);
